# Generated by Django 4.1.5 on 2023-01-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnage',
            old_name='Moral',
            new_name='PointsMax',
        ),
        migrations.RemoveField(
            model_name='personnage',
            name='MoralMax',
        ),
        migrations.RemoveField(
            model_name='personnage',
            name='PointsRestant',
        ),
        migrations.RemoveField(
            model_name='personnage',
            name='Pp',
        ),
        migrations.RemoveField(
            model_name='personnage',
            name='PpMax',
        ),
        migrations.RemoveField(
            model_name='personnage',
            name='Pv',
        ),
        migrations.RemoveField(
            model_name='personnage',
            name='PvMax',
        ),
    ]
