# Generated by Django 4.1.5 on 2023-01-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0002_rename_moral_personnage_pointsmax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='Quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Inventaire',
        ),
    ]
