# Generated by Django 4.1.5 on 2023-01-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0004_personnage_joueur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='caracteristique',
            name='Couleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.couleur'),
        ),
    ]
