# Generated by Django 4.1.5 on 2023-01-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0005_couleur_caracteristique_couleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='personnage',
            name='Role',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='Proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.personnage'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.village'),
        ),
        migrations.AddField(
            model_name='personnage',
            name='Village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.village'),
        ),
    ]
