# Generated by Django 4.1.5 on 2023-01-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0006_village_personnage_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='Proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.personnage'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='Village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.village'),
        ),
    ]
