# Generated by Django 4.1.5 on 2023-01-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0007_alter_equipement_proprietaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeQuete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Quete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=64)),
                ('Statut', models.CharField(max_length=64)),
                ('Recompense', models.CharField(max_length=64)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Irori.typequete')),
            ],
        ),
    ]
