# Generated by Django 4.1.5 on 2023-03-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0010_remove_typequete_proprietaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='Description',
        ),
    ]
