# Generated by Django 4.1.5 on 2023-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0011_remove_equipement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristique',
            name='PointsMax',
            field=models.IntegerField(null=True),
        ),
    ]
