# Generated by Django 4.1.5 on 2023-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0013_lancerdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancerdes',
            name='Bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lancerdes',
            name='Taille',
            field=models.IntegerField(default=20),
        ),
    ]
