# Generated by Django 4.1.5 on 2023-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0014_lancerdes_bonus_lancerdes_taille'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancerdes',
            name='Session',
            field=models.IntegerField(default=1),
        ),
    ]
