# Generated by Django 4.1.5 on 2023-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0016_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancerdes',
            name='Version',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='village',
            name='Version',
            field=models.IntegerField(default=3),
        ),
    ]
