# Generated by Django 4.1.5 on 2023-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0018_alter_lancerdes_version_alter_village_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Version',
            field=models.IntegerField(default=3),
        ),
    ]
