# Generated by Django 4.1.5 on 2023-11-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0019_session_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Version',
            field=models.IntegerField(default=4),
        ),
    ]
