# Generated by Django 4.1.5 on 2023-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0020_alter_session_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='quete',
            name='Version',
            field=models.IntegerField(default=3),
        ),
    ]
