# Generated by Django 4.1.5 on 2023-11-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0022_alter_quete_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancerdes',
            name='Action',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='lancerdes',
            name='Perso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.personnage'),
        ),
    ]
