# Generated by Django 4.1.5 on 2023-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0023_lancerdes_action_lancerdes_perso'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancerdes',
            name='Des',
            field=models.CharField(default='', max_length=64),
        ),
    ]
