# Generated by Django 4.1.5 on 2023-11-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0024_lancerdes_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancerdes',
            name='Couleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Irori.couleur'),
        ),
    ]
