# Generated by Django 4.1.5 on 2023-11-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Irori', '0025_lancerdes_couleur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnage',
            name='PointsMax',
        ),
    ]
